name: kgrill_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

#Packages
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  lottie: ^3.1.2
  url_launcher: ^6.2.6
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  jose: ^0.3.4
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Icons Packages
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1

  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  #Google Signin
  google_sign_in: ^6.2.1

#Product Specific

#Packages end here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/kgrill-logo.png"
  adaptive_icon_foreground: "assets/logos/kgrill-logo.png"
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true

  # Local assets
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/email_verification/
    - assets/images/password_reset/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/products/
    - assets/images/loading/
    - assets/images/icons/
    - lib/.env

  # Local fonts:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

